### PR TITLE
XML cleanup

### LINKED ISSUE #1860: [Bug]: Transform Get Subfolders is broken
### Apache Hop version?

2.2.0

### Java version?

openjdk version "11.0.17" 2022-10-18

### Operating system

Linux

### What happened?

With any folder you specify you get over 1000 rows on output until you get a stack overflow error:

```
2022/12/01 12:24:03 - Get subfolder names.0 - ERROR: java.lang.StackOverflowError
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.ui.hopgui.file.pipeline.HopGuiPipelineGraph$4.rowWrittenEvent(HopGuiPipelineGraph.java:4200)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.handlePutRow(BaseTransform.java:1065)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transform.BaseTransform$DefaultRowHandler.putRow(BaseTransform.java:3794)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transform.BaseTransform.putRow(BaseTransform.java:1010)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transforms.getsubfolders.GetSubFolders.processRow(GetSubFolders.java:202)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transforms.getsubfolders.GetSubFolders.processRow(GetSubFolders.java:206)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transforms.getsubfolders.GetSubFolders.processRow(GetSubFolders.java:206)
2022/12/01 12:24:03 - Get subfolder names.0 - 	at org.apache.hop.pipeline.transforms.getsubfolders.GetSubFolders.processRow(GetSubFolders.java:206)
```

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

### PR DESCRIPTION
**Pull request by mattcasters**
HOP-4308 : Cleanup XML of transform Get Sub Folders
HOP-4373 : Cleanup XML of action Check DB Connections
HOP-4379 : Cleanup XML of action Create Folder

#1859 : Sonar Vulnerability issues
#1860 : Transform Get Subfolders is broken
#1862 : Cleanup XML of Azure Event Hubs Listener task
#1863 : Cleanup XML of Azure Event Hubs Write
#1867 : Cleanup XML of transform Execute Process
#1869 : Cleanup XML of transform Get table names
#1894 : Cleanup XML of transform Replace String
#1895 : Cleanup XML of transform Reservoir Sampling

### CODE REVIEW

File: plugins/actions/setvariables/src/test/java/org/apache/hop/workflow/actions/setvariables/WorkflowEntrySetVariablesTest.java [hunk 1]
```diff
@@ -46,10 +46,7 @@
 import java.io.RandomAccessFile;
 import java.nio.charset.StandardCharsets;
 
-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertNull;
-import static org.junit.Assert.assertTrue;
-import static org.junit.Assert.fail;
+import static org.junit.Assert.*;
```
Comment (hansva) [inline plugins/actions/setvariables/src/test/java/org/apache/hop/workflow/actions/setvariables/WorkflowEntrySetVariablesTest.java:49]: star import introduced

**Review by hansva — CHANGES_REQUESTED** [review]

**Comment by mattcasters** [comment]
Thanks!  Looks like an IntelliJ bug since I've had start imports disabled for quite a while now.

**Comment by mattcasters** [comment]
Apparently there are default exceptions for java.awt.* and static imports.
